ALTER TABLE "Chatbot" ADD COLUMN IF NOT EXISTS "customModel" TEXT;
ALTER TABLE "Chatbot" ADD COLUMN IF NOT EXISTS "customApiKey" TEXT;
ALTER TABLE "Chatbot" ADD COLUMN IF NOT EXISTS "allowedOrigins" TEXT[] NOT NULL DEFAULT '{}';
